POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test title",
  "author": "famous author",
  "url": "http://website.com",
  "likes": 22,
  "userId": "671785b77dbf7b3a1506cf8c"
}